FORMAT: 1A
HOST: http://www.google.com

# cs373-idb
**cs373-idb**

# Group Country

## Country Collection [/country]
### List all Countries [GET]
+ Response 200 (application/json)

        [{
          "name": "Southern USA"
        }, {
          "name": "China"
        }, {
          "name": "Mexico"
        }, {
          "name": "Austria"
        }, {
          "name": "Italy"
        }, {
          "name": "India"
        }, {
          "name": "Great Britain"
        }, {
          "name": "France"
        }, {
          "name": "Greece"
        }, {
          "name": "Japan"
        }]

## Country [/country/name/{name}]
    A single Country object with its food
    
### Country by name[GET]
+ Parameters
    + name (required, string, `China`) ... Numeric `name` of the Country to perform action with.

+ Response 200 (application/json)

    + Header

            X-My-Header: The Name

    + Body

            [{ "name": "Southern USA", 
            "description": "Southern USA food is derived from many cultures. 
                    Many items such as squash, tomatoes, corn (and its derivatives, 
                    including grits), as well as the practice of deep pit barbecuing 
                    were inherited from the southeastern American Indian tribes such 
                    as the Caddo, Choctaw, and Seminole. Many foods associated with 
                    sugar, flour, milk, eggs (many kinds of baking or dairy products 
                    such as breads and cheeses) are more associated with Europe. 
                    Black-eyed peas, okra, rice, eggplant, benne (sesame) seed, sorghum, 
                    and melons, as well as the spices can be attributed to peoples 
                    of African origin.",
            "google_map": "https://www.google.com/maps/place/United+States/@36.5834655,-93.1601172,4z/data=!4m2!3m1!1s0x54eab584e432360b:0x1c3bb99243deb742"},
            { "name": "China", 
            "description": "Rice is China's staple food. The Chinese word for rice 
                    is "fan" which also means "meal." Rice may be served with any meal, and 
                    is eaten several times a day. Scallions, bean sprouts, cabbage, and gingerroot
                    are other traditional foods. Soybean curd, called tofu, is an important 
                    source of protein for the Chinese. Although the Chinese generally do not eat 
                    a lot of meat, pork and chicken are the most commonly eaten meats. Vegetables 
                    play a central role in Chinese cooking, too.",
            "google_map": "https://www.google.com/maps/place/China/@35.8574708,104.1361118,4z/data=!3m1!4b1!4m2!3m1!1s0x31508e64e5c642c1:0x951daa7c349f366f"},
            { "name": "Mexico", 
            "description": "Mexican cuisine is primarily a fusion of indigenous 
                    Mesoamerican cooking with European, especially Spanish, elements added 
                    after the Spanish conquest of the Aztec Empire in the 16th century. The 
                    basic staples remain native foods such as corn, beans and chili peppers, 
                    but the Europeans introduced a large number of other foods, the most 
                    important of which were meat from domesticated animals (beef, pork, 
                    chicken, goat and sheep), dairy products (especially cheese) and various 
                    herbs and lots of spices.",
            "google_map": "https://www.google.com/maps/place/Mexico/@23.6266557,-102.5375005,5z/data=!3m1!4b1!4m2!3m1!1s0x84043a3b88685353:0xed64b4be6b099811"},
            { "name": "Austria", 
            "description": "Austrian cuisine is a style of cuisine native to Austria and 
                    composed of influences from throughout the former Austro-Hungarian Empire.
                    Regional influences from Italy, Hungary, Bohemia, Germany and the Balkans 
                    have had an effect on Austrian cooking, and in turn this fusion of styles
                    was influential throughout the Empire.",
            "google_map": "https://www.google.com/maps/place/Austria/@47.6964719,13.3457347,7z/data=!3m1!4b1!4m2!3m1!1s0x476d079b259d2a7f:0x1012d47bdde4c1af"},
            { "name": "Italy", 
            "description": "Italian cuisine is characterized by its simplicity, with many
                    dishes having only four to eight ingredients.[8] Italian cooks rely chiefly 
                    on the quality of the ingredients rather than on elaborate preparation. 
                    Ingredients and dishes vary by region. Many dishes that were once regional, 
                    however, have proliferated with variations throughout the country. In 2013 
                    Italian cuisine was ranked by CNN as the best cuisine in the world.",
            "google_map": "https://www.google.com/maps/place/Italy/@41.29246,12.5736108,6z/data=!3m1!4b1!4m2!3m1!1s0x12d4fe82448dd203:0xe22cf55c24635e6f"},
            { "name": "India", 
            "description": "Indian cuisine encompasses a wide variety of regional cuisines 
                    native to India. Given the range of diversity in soil type, climate and occupations, 
                    these cuisines vary significantly from each other and use locally available spices,
                    herbs, vegetables and fruits. Indian food is also heavily influenced by religious
                    and cultural choices and traditions.",
            "google_map": "https://www.google.com/maps/place/India/@21.1289955,82.7792201,5z/data=!3m1!4b1!4m2!3m1!1s0x30635ff06b92b791:0xd78c4fa1854213a6"},
            { "name": "Great Britain", 
            "description": "British food has traditionally been based on beef, lamb, pork, 
                    chicken and fish and generally served with potatoes and one other vegetable. The
                    most common and typical foods eaten in Britain include the sandwich, fish and 
                    chips, pies like the cornish pasty, trifle and roasts dinners.",
            "google_map": "https://www.google.com/maps/place/United+Kingdom/@55.3617609,-3.4433238,6z/data=!3m1!4b1!4m2!3m1!1s0x25a3b1142c791a9:0xc4f8a0433288257a"},
            { "name": "France", 
            "description": "Guillaume Tirel Taillevent, a court chef, wrote Le Viandier, one 
                    of the earliest recipe collections of medieval France. During that time, French 
                    cuisine was heavily influenced by Italian cuisine. In the 17th century, chefs 
                    François Pierre La Varenne and Marie-Antoine Carême spearheaded movements that 
                    shifted French cooking away from its foreign influences and developed France's
                    own indigenous style. Cheese and wine are a major part of the cuisine, playing
                    different roles regionally and nationally, with many variations and appellation
                    d'origine contrôlée (AOC) (regulated appellation) laws.",
            "google_map": "https://www.google.com/maps/place/France/@46.71109,1.7191036,6z/data=!3m1!4b1!4m2!3m1!1s0xd54a02933785731:0x6bfd3f96c747d9f7"},
            { "name": "Greece", 
            "description": "Greek cuisine is a Mediterranean cuisine. Contemporary Greek cookery 
                    makes wide use of olive oil, vegetables and herbs, grains and bread, wine, fish, and 
                    various meats, including lamb, poultry, rabbit and pork. Also important are olives, 
                    cheese, eggplant (aubergine), zucchini (courgette), and yogurt. Greek desserts are 
                    characterized by the dominant use of nuts and honey. Some dishes use filo pastry.",
            "google_map": "https://www.google.com/maps/place/Greece/@38.2749497,23.8102717,7z/data=!3m1!4b1!4m2!3m1!1s0x135b4ac711716c63:0x363a1775dc9a2d1d"},
            { "name": "Japan", 
            "description": "The traditional food of Japan is based on rice with miso soup and other 
                    dishes, each in its own utensil, with an emphasis on seasonal ingredients. The side dishes 
                    often consist of fish, pickled vegetables, and vegetables cooked in broth. Fish is common 
                    in the traditional cuisine. It is often grilled, but it may also be served raw as sashimi 
                    or in sushi. Seafood and vegetables are also deep-fried in a light batter as tempura.",
            "google_map": "https://www.google.com/maps/place/Japan/@37.4900318,136.4664008,6z/data=!3m1!4b1!4m2!3m1!1s0x34674e0fd77f192f:0xf54275d47c665244"},]


# Group Recipe

##Recipe Collection [/recipe]
### List all Recipes [GET]
+ Response 200 (application/json)

        [{
            "name": "Southern Fried Chicken"
        }, {
            "name": "Dry-Fried Eggplant"
        }, {
            "name": "Pico de Gallo"
        } {
            "name": "Beef Goulash"
        }, {
            "name": "Chicken Piccata"
        }, {
            "name": "Chicken Tikka Masala"
        }, {
            "name": "Pork and Ham Pie"
        }, {
            "name": "Crepes Suzette"
        }, {
            "name": "Tzatziki"
        }, {
            "name": "Vegetable Sushi"
        },]

## Recipe [/recipe/name/{name}]
    Steps of how to make food

###Recipe by name[GET]
+ Parameters
    + name(required, string, `pizza`) ... Numeric `name` of the Food to perform action with.

+ Response 200 (application/json)

    + Header

            X-My-Header: The Name

    + Body

            [{ "name": "Southern Fried Chicken", 
            "ingredients": "3 eggs 1/3 cup water
                    About 1 cup hot red pepper sauce (recommended: Texas Pete)
                    2 cups self-rising flour
                    1 teaspoon pepper
                    House seasoning, recipe follows
                    1 (1 to 2 1/2-pound) chicken, cut into pieces
                    Oil, for frying, preferably peanut oil
                    
                    House Seasoning:
                    1 cup salt
                    1/4 cup black pepper
                    1/4 cup garlic powder ", 
            "region": "Southern USA",
            "chef": "Paula Deen",
            "instructions": "1. In a medium size bowl, beat the eggs with the water. Add enough hot sauce so the egg mixture is bright orange. In another bowl, combine the flour and pepper. Season the chicken with the house seasoning. Dip the seasoned chicken in the egg, and then coat well in the flour mixture.
        
                            2. Heat the oil to 350 degrees F in a deep pot. Do not fill the pot more than 1/2 full with oil.
                            
                            3. Fry the chicken in the oil until brown and crisp. Dark meat takes longer then white meat. It should take dark meat about 13 to 14 minutes, white meat around 8 to 10 minutes.
                            
                            4. House Seasoning: Mix ingredients together and store in an airtight container for up to 6 months.",
            "time needed": "1 hour",
            "difficulty": "E",
            "type": "entree"},
            { "name": "Dry-Fried Eggplant", 
            "ingredients": " Vegetable oil, for frying
                            1/2 to 1 teaspoon hot (chinese) chili powder
                            1/2 to 1 teaspoon hot paprika
                            About 6 (1 1/2 pounds total) Chinese (long) eggplants, trimmed, peeled and cut lengthwise into 2- or 3-inch-long, thick "steak" fries (about 8 fries from each eggplant)
                            Water
                            1/2 cup cornstarch
                            Leaves and tender stems from 4 to 6 stems cilantro, coarsely chopped", 
            "region": China,
            "chef": Peter Chang,
            "instructions": "Heat at least 4 inches of oil in a large, heavy-bottomed pot over medium-high heat until the oil reaches 350 degrees.
                    
                    Place a wire rack over several layers of paper towels.
                    
                    Combine the chili powder and paprika (to taste) in a small bowl.
                    
                    Meanwhile, wet the eggplant fries with a little water. Spread the cornstarch on a rimmed baking sheet.
                    
                    Working in batches, lightly and evenly coat the eggplant fries with the cornstarch, shaking off any excess. Discard any remaining cornstarch.
                    
                    Carefully add about 8 fries at a time to the hot oil; fry for 2 minutes, or until just browned, crisped and tender. Use a Chinese skimmer or slotted spatula to transfer to the rack to drain. Repeat to fry all the eggplant.
                    
                    Transfer the still-warm, crisped eggplant fries to a serving bowl; season with the chili powder-paprika mixture to taste; this dish is supposed 
                    
                    to be spicy, and, if you can stand it, you should use enough of the mixture to color the eggplant fries a reddish-orange. Toss quickly with the cilantro; serve right away.",
            "time needed": "~20 min",
            "difficulty": "E",
            "type": "side"},
            { "name": "Pico de Gallo", 
            "ingredients": "1 1/2 pounds yellow or red tomatoes, seeded and chopped
                            1 small onion, chopped
                            1/2 cup chopped fresh cilantro leaves
                            3 tablespoons fresh lime juice
                            2 serrano chiles*, seeded and minced
                            Pinch kosher salt and fresh ground black pepper", 
            "region": "Mexico",
            "chef": "Marcela Valladolid",
            "instructions": "Add all the ingredients to a medium bowl, and toss to combine.
                            Cover and chill until ready to serve. This salsa can be made 4 hours ahead.",
            "time needed": "40 min",
            "difficulty": "E",
            "type": "side"},
            { "name": "Beef Goulash", 
            "ingredients": "2 tablespoons extra virgin olive oil
                            4 cups onions, thinly sliced
                            1 tablespoon sugar
                            3 garlic cloves, minced
                            1 tablespoon caraway seeds, toasted and ground
                            1 1/2 tablespoons sweet paprika
                            1 teaspoon spicy paprika
                            2 tablespoons minced fresh marjoram leaves
                            1 teaspoon minced fresh thyme leaves
                            1 bay leaf
                            3 tablespoons tomato paste
                            2 tablespoons balsamic vinegar
                            4 cups chicken stock
                            2 1/2 pounds beef shank, cut into 2-inch cubes
                            1 teaspoon kosher salt
                            1/4 teaspoon freshly ground black pepper
                            Spaetzle, recipe follows
                            Spaetzle:
                            4 egg yolks
                            1 egg
                            1 3/4 cups milk
                            1 pound (about 3 cups) all purpose flour
                            1/4 teaspoon freshly grated nutmeg
                            1 teaspoon salt
                            1/4 teaspoon freshly ground pepper
                            1/2 cup peanut oil
                            Salt
                            Pepper
                            2 ounces unsalted butter", 
            "region": "Southern USA",
            "chef": "Wolfgang Puck",
            "instructions": "In a large saute pan, heat the olive oil and saute the onions and sugar until caramelized. Add the garlic and caraway seed. 
            
                            Cook for 1 minute. Add the sweet and sharp paprika, marjoram, thyme, and bay leaf. Saute another minute, until fragrant. Add the tomato paste. 
                            
                            Deglaze with the vinegar and the stock and add the pieces of beef shank, salt, and pepper. Bring to a boil, then lower to a simmer and cook until very tender, about 1 1/2 hours, stirring occasionally.

                            Taste and adjust seasoning with salt and pepper. Serve with Spaetzle on the side.
                            
                            Spaetzle:
                            
                            In a small bowl, beat together the egg yolks, egg and milk. In a medium bowl, combine the flour, nutmeg, salt, and pepper.
                            
                            Add the egg mixture to the flour mixture and mix with hand until well blended. Do not overmix at this stage. Cover the bowl and refrigerate. Allow the batter to rest for at least 1 hour.
                            
                            Bring salted water to a boil. Place a perforated hotel pan on top of the pot. Place the batter on the pan and force through the holes to form spaetzle. Cook for 4 to 5 minutes, or until al dente. Transfer cooked spaetzle to a bowl of ice water to shock. When cool to the touch, drain well. Stir in half the oil. (At this point you can cover and refrigerate up to 2 days).
                            
                            Over high heat, place a large saute pan until it gets very hot. Add the remaining 1/4 cup of oil and the boiled spaetzle. Saute until golden. Season, to taste, with salt and pepper. Finish with butter and sprinkle with parsley.",
            "time needed": "1 hour",
            "difficulty": "easy",
            "type": "dessert"},
            { "name": "Southern Fried Chicken", 
            "ingredients": "", 
            "region": "Southern USA",
            "chef": "Paula Deen",
            "instructions": "",
            "time needed": "1 hour",
            "difficulty": "easy",
            "type": "dessert"},
            { "name": "Southern Fried Chicken", 
            "ingredients": "", 
            "region": "Southern USA",
            "chef": "Paula Deen",
            "instructions": "",
            "time needed": "1 hour",
            "difficulty": "easy",
            "type": "dessert"},
            { "name": "Southern Fried Chicken", 
            "ingredients": "", 
            "region": "Southern USA",
            "chef": "Paula Deen",
            "instructions": "",
            "time needed": "1 hour",
            "difficulty": "easy",
            "type": "dessert"},
            { "name": "Southern Fried Chicken", 
            "ingredients": "", 
            "region": "Southern USA",
            "chef": "Paula Deen",
            "instructions": "",
            "time needed": "1 hour",
            "difficulty": "easy",
            "type": "dessert"},
            { "name": "Southern Fried Chicken", 
            "ingredients": "", 
            "region": "Southern USA",
            "chef": "Paula Deen",
            "instructions": "",
            "time needed": "1 hour",
            "difficulty": "easy",
            "type": "dessert"},
            { "name": "Southern Fried Chicken", 
            "ingredients": "", 
            "region": "Southern USA",
            "chef": "Paula Deen",
            "instructions": "",
            "time needed": "1 hour",
            "difficulty": "easy",
            "type": "dessert"}]
            
# Group Chef

##Chef Collection [/chef]
### List all Chefs [GET]
+ Response 200 (application/json)

        [{
            "name": "Paula Deen"
        }, {
            "name": "Peter Chang"
        }, {
            "name": "Marcela Valladolid"
        }, {
            "name": "Wolfgang Puck"
        }, {
            "name": "Giada De Laurentiis"
        },{
            "name": "Aarti Sequeira"
        },{
            "name": "Gordon Ramsay"
        },{
            "name": "Jacques Pepin"
        },{
            "name": "Michael Psilakis"
        },{
            "name": "Masaharu Morimoto"
        },]

## Chef [/chef/name/{name}]
    Chef of each country

###Chef by name[GET]
+ Parameters
    + name(required, string, `Tom`) ... Numeric `name` of the Chef to perform action with.

+ Response 200 (application/json)

    + Header

            X-My-Header: The Name

    + Body

            [{ "name": "Paula Deen", 
            "region": "Southern USA,
            "birth_place": Albany, Georgia, U.S.,
            "birth_date": "19 January 1947",
            "youtube":"https://www.youtube.com/watch?v=ogknIyLESHc",
            "twitter": "https://twitter.com/Paula_Deen"
            "bio":Paula Ann Hiers Deen is an American celebrity chef and cooking show television host. 
                    Deen resides in Savannah, Georgia, where she owns and operates The Lady & Sons 
                    restaurant with her sons, Jamie and Bobby Deen. She has published fourteen cookbooks. 
                    Though married in 2004 to Michael Groover, she uses the surname Deen, from her first marriage},
            { "name": "Peter Chang", 
            "region": "China",
            "birth_place":,
            "birth_date": "1990",
            "youtube": "http://www.youtube.com/watch?v=dsffikBdjz8",
            "twitter": "https://twitter.com/sichuanboy"'
            "bio": "Peter Chang is an award winning chef specializing in Szechwan cuisine who has cooked 
                    for restaurants in the American southeast. Chang was born in Hubei Province and trained in 
                    China, and cooked a meal for the Chinese president, Hu Jintao.[1] He moved to the United States 
                    to work as the chef at the Chinese Embassy in Washington, D.C.[1] In the past, Chang has disappeared
                    and left restaurants, inspiring a group of fans to follow his movement in Internet discussion boards, 
                    such as DonRockwell.com and Chowhound."},
            { "name": "Marcela Valladolid", 
            "region": "Mexico",
            "birth_place": "San Diego, California",
            "birth_date": "19 July 1978",
            "youtube": "http://www.youtube.com/watch?v=OePrgATo0f4",
            "twitter": "https://twitter.com/chefmarcela",
            "bio": "Marcela Luz Valladolid is an American chef and author. She is the host of the Food Network television 
                    series Mexican Made Easy, and a co-host of the Food Network television series The Kitchen."},
            { "name": "Wolfgang Puck", 
            "region": "Austria",
            "birth_place": "Sankt Veit an der Glan, Austria",
            "birth_date": "8 July 1949",
            "youtube":"http://www.youtube.com/watch?v=Gc6B_N4eRoA",
            "twitter": "https://twitter.com/WolfgangBuzz"
            "bio": "Wolfgang Johannes Puck (born Wolfgang Johannes Topfschnig; July 8, 1949) is an Austrian-born American 
                    celebrity chef, restaurateur, and occasional actor. Wolfgang Puck restaurants, catering services, cookbooks 
                    and licensed products are run by Wolfgang Puck Companies, with three divisions."},
            { "name": "Giada De Laurentiis", 
            "region": "Italy",
            "birth_place": "Rome, Italy",
            "birth_date": "22 August 1970",
            "youtube":"http://www.youtube.com/watch?v=nI8DlJ_4MV0",
            "twitter": "https://twitter.com/GDeLaurentiis",
            "bio": "Giada Pamela De Laurentiis (Italian pronunciation: [ˈdʒaːda de lauˈrentis]; born August 22, 1970) is an 
                    Italian-born American chef, writer, television personality, and the host of the current Food Network television 
                    program Giada at Home. She also appears regularly as a contributor and guest co-host on NBC's Today. De Laurentiis
                    is the founder of the catering business GDL Foods.[1] She is a winner of the Daytime Emmy Award for Outstanding 
                    Lifestyle Host,[2] and in 2012 was inducted into the Culinary Hall of Fame."},
            { "name": "Aarti Sequeira", 
            "region": "India",
            "birth_place": "Mumbai, India",
            "birth_date": "19 August 1978",
            "youtube": "http://www.youtube.com/watch?v=3LFFpAD15Y8",
            "twitter": "https://twitter.com/aartipaarti",
            "bio": "Aarti Sequeira is an Indian chef and television personality, best known as the winner of the sixth season 
                    of Food Network's reality television show, The Next Food Network Star.[1] As a result of that victory, her show 
                    Aarti Party premiered on the network on August 22, 2010. She had previously worked as a CNN news producer and in
                    2008 started the online cooking variety show Aarti Paarti. She currently hosts another cooking show, Taste in 
                    Translation,[1] in which she seeks the most popular dishes from around the world."},
            { "name": "Gordon Ramsay", 
            "region": "Great Britain",
            "birth_place": "Johnstone, Renfrewshire, Scotland",
            "birth_date": "8 November 1966",
            "youtube": "https://www.youtube.com/watch?v=fETZCWvzkWM",
            "twitter": "https://twitter.com/GordonRamsay",
            "bio": "Gordon James Ramsay, Jr. /ˈræm.ziː/, OBE (born 8 November 1966) is a Scottish celebrity chef, restaurateur, 
                    and television personality.[1] His restaurants have been awarded 15 Michelin stars in total and currently hold 
                    14. His signature restaurant, Restaurant Gordon Ramsay in Chelsea, London has held 3 Michelin stars since 2001.
                    Ramsay is known for presenting TV programmes about competitive cookery and food, such as the British series Hell's 
                    Kitchen, The F Word, and Ramsay's Kitchen Nightmares, along with the American versions of Hell's Kitchen, Kitchen 
                    Nightmares, MasterChef, and Masterchef Junior."},
            { "name": "Jacques Pepin", 
            "region": "France",
            "birth_place": "Bourg-en-Bresse, France",
            "birth_date": "18 December 1935",
            "youtube": "http://www.youtube.com/watch?v=Ysm-LEEb_K4",
            "twitter": "https://twitter.com/jacques_pepin"'
            "bio": "Jacques Pépin (born December 18, 1935)[1] is an internationally recognized French chef, television personality, 
                    and author working in the United States. Since the late 1980s, he has appeared on French and American television and 
                    written an array of cookbooks that have become best sellers."},
            { "name": "Michael Psilakis", 
            "region": "Greece",
            "birth_place": "New York City, NY",
            "birth_date": "1968",
            "youtube":"http://www.youtube.com/watch?v=mIYCManR3Ec",
            "twitter": "https://twitter.com/MPsilakis",
            "bio":"Michael Psilakis is a Greek-American New York City restaurateur best known for his appearances on television shows 
                    including Ultimate Recipe Showdown, Iron Chef America, The Best Thing I Ever Ate and No Kitchen Required.[1] He had 
                    owned and operated a number of popular restaurants around New York and has cooked for President Barack Obama at the White House."},
            { "name": "Masaharu Morimoto", 
            "region": "Japan",
            "birth_place": "Hiroshima, Japan",
            "birth_date": "1955",
            "youtube": "https://www.youtube.com/watch?v=WmaTpRuQFTE",
            "twitter": "https://twitter.com/chef_morimoto",
            "bio": "Masaharu Morimoto (森本 正治 Morimoto Masaharu?, born May 26, 1955, in Hiroshima, Japan) is a Japanese chef, 
                    best known as an Iron Chef on the Japanese TV cooking show Iron Chef and its spinoff Iron Chef America. He is also known for his unique
                    style of presenting food. Morimoto received practical training in sushi and traditional Kaiseki cuisine in Hiroshima, and opened his own 
                    restaurant in that city in 1980. Influenced by Western cooking styles, he decided to sell his restaurant in 1985 to travel around the 
                    United States. His travels further influenced his fusion style of cuisine. He established himself in New York City and worked in some
                    of Manhattan's prestigious restaurants, including the dining area for Sony Corporation's executive staff and visiting VIPs, the Sony Club, 
                    where he was executive chef, and at the exclusive Japanese restaurant Nobu, where he was head chef. While at Nobu he got his start on 
                    the Iron Chef television show. Several months after the weekly run of Iron Chef ended in 1999, he left Nobu, eventually opening his 
                    own Morimoto restaurant in Philadelphia in 2001. He now has a Morimoto restaurant in Chelsea in New York City. For this New York City 
                    restaurant it has architecturally exposed concrete, a signature element of Tadao Ando’s work, is dramatically visible in a series.
                    Alongside Tadao Ando and collaboration with Goto Design Group, the structural engineers who took on this project was Leslie E. Robertson 
                    Associates. Mr. Morimoto also has restaurants in Mumbai and New Delhi, called "Wasabi" and another Morimoto in Boca Raton, Florida. 
                    He also partnered with businessmen Paul Ardaji, Jr., and Paul Ardaji, Sr., in an Asian bistro venture called Pauli Moto's; the initial 
                    branch opened in Tyson's Corner, Virginia but has since closed.[2] Morimoto also owns Morimoto XEX in Tokyo that has a Teppanyaki and 
                    a sushi floor. Morimoto XEX received a Michelin star in the recent Tokyo Michelin Guide.[3] Morimoto currently appears as an Iron Chef 
                    in Iron Chef America, a spinoff from the original Japanese Iron Chef series. "}]

+ Response 204

