FORMAT: 1A
HOST: http://www.google.com

# cs373-idb
**cs373-idb**

# Group Country

## Country Collection [/country]
### List all Countries [GET]
+ Response 200 (application/json)

        [{
          "name": "Southern USA"
        }, {
          "name": "China"
        }, {
          "name": "Mexico"
        }, {
          "name": "Austria"
        }, {
          "name": "Italy"
        }, {
          "name": "India"
        }, {
          "name": "Great Britain"
        }, {
          "name": "France"
        }, {
          "name": "Greece"
        }, {
          "name": "Japan"
        }]

## Country [/country/name/{name}]
    A single Country object with its food
    
### Country by name[GET]
+ Parameters
    + name (required, string, `China`) ... Numeric `name` of the Country to perform action with.

+ Response 200 (application/json)

    + Header

            X-My-Header: The Name

    + Body

            [{ "name": "America", 
            "description": "Something about American food",
            "location": "North America", 
            "picture": "http://A.picture" },
            { "name": "China", 
            "description": "Something about Chinese food",
            "location": "Asia", 
            "picture": "http://C.picture" },
            { "name": "Mexican", 
            "description": "Something about Mexican food",
            "location": "North America", 
            "picture": "http://M.picture" }]


# Group Recipe

##Recipe Collection [/recipe]
### List all Recipes [GET]
+ Response 200 (application/json)

        [{
            "name": "Southern Fried Chicken"
        }, {
            "name": "Dry-Fried Eggplant"
        }, {
            "name": "Pico de Gallo"
        } {
            "name": "Beef Goulash"
        }, {
            "name": "Chicken Piccata"
        }, {
            "name": "Chicken Tikka Masala"
        }, {
            "name": "Pork and Ham Pie"
        }, {
            "name": "Crepes Suzette"
        }, {
            "name": "Tzatziki"
        }, {
            "name": "Vegetable Sushi"
        },]

## Recipe [/recipe/name/{name}]
    Steps of how to make food

###Recipe by name[GET]
+ Parameters
    + name(required, string, `pizza`) ... Numeric `name` of the Food to perform action with.

+ Response 200 (application/json)

    + Header

            X-My-Header: The Name

    + Body

            [{ "name": "f1", 
            "ingredients": "A", 
            "region": ,
            "chef": ,
            "instructions": "first..",
            "time needed": "1 hour",
            "difficulty": "easy",
            "type": "dessert",
            "picture": "http://f1.picture" },
            { "name": "Dry-Fried Eggplant", 
            "ingredients": " Vegetable oil, for frying
                            1/2 to 1 teaspoon hot (chinese) chili powder
                            1/2 to 1 teaspoon hot paprika
                            About 6 (1 1/2 pounds total) Chinese (long) eggplants, trimmed, peeled and cut lengthwise into 2- or 3-inch-long, thick "steak" fries (about 8 fries from each eggplant)
                            Water
                            1/2 cup cornstarch
                            Leaves and tender stems from 4 to 6 stems cilantro, coarsely chopped", 
            "region": China,
            "chef": Peter Chang,
            "instructions": "Heat at least 4 inches of oil in a large, heavy-bottomed pot over medium-high heat until the oil reaches 350 degrees.
                    
                    Place a wire rack over several layers of paper towels.
                    
                    Combine the chili powder and paprika (to taste) in a small bowl.
                    
                    Meanwhile, wet the eggplant fries with a little water. Spread the cornstarch on a rimmed baking sheet.
                    
                    Working in batches, lightly and evenly coat the eggplant fries with the cornstarch, shaking off any excess. Discard any remaining cornstarch.
                    
                    Carefully add about 8 fries at a time to the hot oil; fry for 2 minutes, or until just browned, crisped and tender. Use a Chinese skimmer or slotted spatula to transfer to the rack to drain. Repeat to fry all the eggplant.
                    
                    Transfer the still-warm, crisped eggplant fries to a serving bowl; season with the chili powder-paprika mixture to taste; this dish is supposed to be spicy, and, if you can stand it, you should use enough of the mixture to color the eggplant fries a reddish-orange. Toss quickly with the cilantro; serve right away.",
            "time needed": "~20 min",
            "difficulty": "E",
            "type": "side",
            "picture": "http://www.washingtonpost.com/rf/image_600w/2010-2019/WashingtonPost/2012/01/14/Food/Images/FDwine25006_1326565800.jpg" },]
            
# Group Chef

##Chef Collection [/chef]
### List all Chefs [GET]
+ Response 200 (application/json)

        [{
            "name": "Paula Deen"
        }, {
            "name": "Peter Chang"
        }, {
            "name": "Marcela Valladolid"
        }, {
            "name": "Wolfgang Puck"
        }, {
            "name": "Giada De Laurentiis"
        },{
            "name": "Aarti Sequeira"
        },{
            "name": "Gordon Ramsay"
        },{
            "name": "Jacques Pepin"
        },{
            "name": "Michael Psilakis"
        },{
            "name": "Masaharu Morimoto"
        },]

## Chef [/chef/name/{name}]
    Chef of each country

###Chef by name[GET]
+ Parameters
    + name(required, string, `Tom`) ... Numeric `name` of the Chef to perform action with.

+ Response 200 (application/json)

    + Header

            X-My-Header: The Name

    + Body

            [{ "name": "Tom", 
            "year born": "1990",
            "country": "America", 
            "twitter feed": "Tom",
            "picture": "http://Tom.picture" },
            { "name": "And", 
            "country": "China", 
            "twitter feed": "And",
            "picture": "http://And.picture" },
            { "name": "Jerry", 
            "country": "Mexican", 
            "twitter feed": "Jerry",
            "picture": "http://Jerry.picture" }]

+ Response 204

